name: Lint & Test
on: [push]
permissions:
  contents: write
  actions: read
  pull-requests: write
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - name: Check VIPWPCS Directory
        run: ls -la vendor/automattic/vipwpcs
      - name: Append VIPWPCS Path
        run: |
          CURRENT_PATHS=$(vendor/bin/phpcs --config-show | grep installed_paths | awk '{print $2}')
          if [ -z "$CURRENT_PATHS" ]; then
            vendor/bin/phpcs --config-set installed_paths vendor/automattic/vipwpcs
          else
            vendor/bin/phpcs --config-set installed_paths "$CURRENT_PATHS,vendor/automattic/vipwpcs"
          fi
          vendor/bin/phpcs -i
          vendor/bin/phpcs --config-show
          composer show -t
          cat vendor/automattic/vipwpcs/ruleset.xml
      - name: Lint
        run: composer lint
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.6
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Start MariaDB
        run: sudo systemctl start mysql
      - name: Setup WP-CLI
        uses: godaddy-wordpress/setup-wp-cli@1
      - name: Install Composer dependencies
        run: | 
          composer install
          chmod +x bin/*.sh
      - name: Test
        run: bash ./bin/phpunit-test.sh